### ISSUE TITLE
Insert 10000 rows slow performance

### ISSUE THREAD

**Issue by isaiasmac** [Nike-Inc/SQift#11]
I'm trying to insert 10.000 rows, but the performance is very slow.

**Example**
```swift
let onDiskConnection = try Connection(storageLocation: .onDisk("path_to_db"))

for i in 1...10000 {
  try connection.execute("INSERT INTO cars VALUES(i, 'Audi', 52642)")
} 
```

Any ideas how can I improve the performance ?

**Comment by johnboker** [comment]
I've not used this but putting an insert in a loop like this will alway be slow.  A potential fix would be to start a transaction before the for loop and end the transaction after the loop is done.

Without specifying the transaction I think by default sqlite will have a transaction around each insert, slowing it down.

**Comment by cnoon** [comment]
Hi @isaiasmac,

I'm going to go ahead and close this issue out due to lack of activity. @johnboker's suggestion is spot on.

Cheers. 🍻
