### ISSUE TITLE
Cannot convert value of type 'Float' to expected argument type 'Binding?' Insert ' as! Binding'

### ISSUE THREAD

**Issue by pylearndl** [Nike-Inc/SQift#22]
How to insert float value?
INSERT INTO table (a,b,c) VALUES (?,?,?).bind("hi","there",50.45)

**Comment by cnoon** [comment]
Hi @pylearndl,

I'd recommend checking out the documentation in the [README](https://github.com/Nike-Inc/SQift#executing-statements). You should be able to find everything you need in there.

Best of luck! 🍻

**Comment by pylearndl** [comment]
Cheers. All it needs is string value in argument.
