### ISSUE TITLE
How do I start?

### ISSUE THREAD

**Issue by SubZane** [Nike-Inc/SQift#23]
I'm lacking documentation...

After installing the pod, do I need to import a lib in order to begin? "import SQift" does not work as SQift cannot be found...

**Comment by cnoon** [comment]
Hi @SubZane,

First I'd follow the instructions in the installation instructions in the [README](https://github.com/Nike-Inc/SQift#cocoapods). If you're still having issues, then I would refer to the CocoaPods [documentation](https://guides.cocoapods.org).

Best of luck! 🍻
