### ISSUE TITLE
Query with LIKE params

### ISSUE THREAD

**Issue by isaiasmac** [Nike-Inc/SQift#9]
I'm trying to do this query:

`let q = "SELECT id, nam FROM table WHERE LIKE('%?%', name)"`
`try connection.query(q, name)`

And get this message: Bind expected 0 parameters, instead received 1.

Anyone have an example with LIKE queries?

Thanks.

**Comment by AtomicCat** [comment]
Turns out the sqlite syntax is a bit quirky there. I found this SO answer: https://stackoverflow.com/questions/1105463/sqlite-binding-within-string-literal

The following seem to work in a unit test:
`connection.query("SELECT * FROM agents WHERE name LIKE '%' || ? || '%'", "Lana")`

**Comment by groue** [comment]
The `||` operator is the SQLite concatenation operator: `SELECT 'foo' || 'bar'` yields the "foobar" string.

What is important to understand here is that SQLite only understands `?` as a parameter when it is a placeholder for a whole *value* (int, double, string, blob, null). On the other side, the `?` in `'%?%'` is just a character in the `'%?%'` string value: it is not a query parameter, and is not processed in any way. See https://www.sqlite.org/lang_expr.html#varparam for more information about SQLite parameters.

So you have two choices for providing the LIKE function its argument:

- build the like pattern in Swift:

    ```swift
    let q = "SELECT id, name FROM table WHERE LIKE(?, name)"
    try connection.query(q, "%\(name)%")
    ```

- let SQLite build the like pattern, as @AtomicCat says:

    ```swift
    let q = "SELECT id, name FROM table WHERE LIKE('%' || ? || '%', name)"
    try connection.query(q, name)
    ```

**Comment by cnoon** [comment]
Thanks @groue! I'm going to go ahead and close this out @isaiasmac. Please feel free to continue the conversation if you continue to have issues.

Cheers. 🍻

**Comment by sobri909** [comment]
It also works if you put the percent marks in the argument. 

```swift
let notes = Stalker.store.notes(
    where: "body LIKE ? AND deleted = 0 ORDER BY date DESC",
    arguments: ["%\(query)%"])
```

(This abstraction ultimately calls `Row.fetchCursor(db, query, arguments: arguments)`)
